# Enables logging of Mongo mapping events
logging.level.org.springframework=info

management.endpoints.access.default=read_only
spring.web.error.include-stacktrace=always
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

#
# Verifier options
#
verifier.originalClientId=Verifier
verifier.clientIdPrefix=pre-registered
verifier.publicUrl=http://localhost:${server.port}
verifier.requestJwt.embed=ByReference
verifier.requestJwt.requestUriMethod=Get
verifier.defaultHttpResponseMode=DirectPostJwt
verifier.maxAge=PT6400M
verifier.presentations.cleanup.maxAge=P10D
verifier.authorizationRequestUri=haip-vp://
verifier.allowedRedirectUriSchemes=https

# clientMetadata parameters
verifier.clientMetadata.vpFormats.sdJwtVc.enabled=true
verifier.clientMetadata.vpFormats.sdJwtVc.sdJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.sdJwtVc.kbJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.msoMdoc.enabled=true

#
# Configuration parameters for validations applied by verifier
# to wallet presentations or in utilities api
#
verifier.validation.sdJwtVc.statusCheck.enabled=true

# SD-JWT-VC Validation configuration
verifier.validation.sdJwtVc.kbJwt.clock.skew=PT5S
verifier.validation.sdJwtVc.typeMetadata.policy=not-used

# SD-JWT VC Type Metadata resolution
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.ttl=PT1H
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.maxEntries=10
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.enabled=false
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.allowedAlgorithms=sha256,sha384,sha512

# transaction data
verifier.transactionData.hashAlgorithm=sha-256

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600